apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: app-core
  name: app-core
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app-core
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: app-core
    spec:
      containers:
        - args:
            - bash
            - -c
            - rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  key: DATABASE_HOST
                  name: test-secret
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: test-secret
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: test-secret
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: SECRET_KEY
                  name: test-secret
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  key: SECRET_KEY_BASE
                  name: test-secret
            - name: RAILS_ENV
              valueFrom:
                secretKeyRef:
                  key: RAILS_ENV
                  name: test-secret
          image: jusnavigandi/jus_core:$COMMIT_SHA1
          imagePullPolicy: Always
          name: app-core
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
              httpHeaders:
                - name: X-Forwarded-Proto
                  value: https
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
              httpHeaders:
                - name: X-Forwarded-Proto
                  value: https
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 3
            failureThreshold: 2
            timeoutSeconds: 15
          resources:
            limits:
              cpu: 300m
            requests:
              cpu: 100m
              memory: 250Mi
          stdin: true
          tty: true
      restartPolicy: Always
      serviceAccountName: ""
status: {}
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: app-core
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: app-core
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
